<<<<<<< HEAD
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018001,'Overwatch',2016,'FPS','In a time of global crisis, an international task force of heroes banded together to restore peace to a war-torn world: OVERWATCH. It ended the crisis and helped to maintain peace in the decades that followed, inspiring an era of exploration, innovation, and discovery.','PC',9.55,'https://www.metacritic.com/game/pc/overwatch');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018002,'PUBG',2017,'PUBG','BATTLEGROUNDS is a competitive survival shooter. Players are dropped into a wide, open area, and they must fight to the death - all while the battlefield shrinks, adding pressure to all in its grip. Use a variety of interesting weapons and vehicles amid the BATTLEGROUNDS.','PC',9.0,'https://www.commonsensemedia.org/game-reviews/playerunknowns-battlegrounds/user-reviews/adult');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018003,'League of Legends',2009,'MOBA','League of Legends is a fast-paced, competitive online game that blends the speed and intensity of an RTS with RPG elements. Two teams of powerful champions, each with a unique design and playstyle, battle head-to-head across multiple battlefields and game modes.','PC',8.0,'https://www.metacritic.com/game/pc/league-of-legends');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018004,'Dead by Daylight',2016,'MOBA','In Dead by Daylight, you play as either a Survivor or a Killer. The Survivors aim is to escape the level, and the Killer’s goal is to stop them. Survivors use their 3rd person camera to look around, while the Killer’s FPS view is much more narrow.','PC',7.5,'https://store.steampowered.com/app/381210/Dead_by_Daylight/');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018005,'Dota 2',2013,'MOBA','Dota 2 is a multiplayer online battle arena (MOBA) video game in which two teams of five players compete to collectively destroy a large structure defended by the opposing team known as the "Ancient", whilst defending their own.','PC',7.45,'https://www.metacritic.com/game/pc/dota-2');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018006,'Taiko Drum Master',2004,'MUG','Taiko: Drum Master, also known as Taiko no Tatsujin: Taiko Drum Master (太鼓の達人 TAIKO DRUM MASTER) in Japan, is a rhythm game developed and published by Namco for the Sony PlayStation 2 as part of the popular Japanese video game franchise Taiko no Tatsujin. It was released in North America in 2004, and Japan in 2005.','PS4',8.85,'https://www.metacritic.com/game/playstation-2/taiko-drum-master');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018007,'Grand Theft Auto V',2014,'Single-Player Game','The game is played from either a third-person or first-person perspective and its world is navigated on foot or by vehicle. Players control the three lead protagonists throughout single-player and switch between them both during and outside missions. The story is centred on the heist sequences, and many missions involve shooting and driving gameplay. A "wanted" system governs the aggression of law enforcement response to players who commit crimes. Grand Theft Auto Online, the games online multiplayer mode, lets up to 30 players engage in a variety of different cooperative and competitive game modes.','PC',9.5,'https://www.metacritic.com/game/pc/grand-theft-auto-v');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018008,'Minecraft',2011,'Single-Player Game','Minecraft is a 2011 sandbox video game created by Swedish game developer Markus Persson and later developed by Mojang. The game allows players to build with a variety of different blocks in a 3D procedurally generated world, requiring creativity from players.','PC',6.65,'https://www.metacritic.com/game/pc/minecraft');
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018009,'Hearthstone',2014,'CAG','The game is a turn-based card game between two opponents, using constructed decks of 30 cards along with a selected hero with a unique power. Players use their limited mana crystals to play abilities or summon minions to attack the opponent, with the goal of destroying the opponents hero.','Nintendo Switch',9,'https://www.commonsensemedia.org/game-reviews/hearthstone');
insert into game (id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018010,'Monster Hunter',2004,'ARPG','Astera acts as a central hub where the player can buy and sell goods, manage their inventory, craft new equipment, and gain new quests. A core facet of Monster Hunter games is the construction and upgrading of armor and weapons at a forge using the monster parts and resources the player has gained from combat.','PC',6.7,'https://www.metacritic.com/game/playstation-4/monster-hunter-world');
=======

insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018001,'Overwatch',2016,'FPS','In a time of global crisis, an international task force of heroes banded together to restore peace to a war-torn world: OVERWATCH. It ended the crisis and helped to maintain peace in the decades that followed, inspiring an era of exploration, innovation, and discovery.','PC',9.55,'https://www.metacritic.com/game/pc/overwatch',)
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018002,'PUBG',2017,'PUBG','BATTLEGROUNDS is a competitive survival shooter. Players are dropped into a wide, open area, and they must fight to the death - all while the battlefield shrinks, adding pressure to all in its grip. Use a variety of interesting weapons and vehicles amid the BATTLEGROUNDS.','PC',9.0,'https://www.commonsensemedia.org/game-reviews/playerunknowns-battlegrounds/user-reviews/adult')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018003,'League of Legends',2009,'MOBA','League of Legends is a fast-paced, competitive online game that blends the speed and intensity of an RTS with RPG elements. Two teams of powerful champions, each with a unique design and playstyle, battle head-to-head across multiple battlefields and game modes.','PC',8.9,'https://www.metacritic.com/game/pc/league-of-legends')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018004,'Dead by Daylight',2016,'MOBA','In Dead by Daylight, you play as either a Survivor or a Killer. The Survivors aim is to escape the level, and the Killer’s goal is to stop them. Survivors use their 3rd person camera to look around, while the Killer’s FPS view is much more narrow.','3.5','PC',8.5,'https://store.steampowered.com/app/381210/Dead_by_Daylight/')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018005,'Dota 2',2013,'MOBA','Dota 2 is a multiplayer online battle arena (MOBA) video game in which two teams of five players compete to collectively destroy a large structure defended by the opposing team known as the "Ancient", whilst defending their own.','PC',9.5,'https://www.metacritic.com/game/pc/dota-2')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018006,'Taiko:Drum Master',2004,'MUG','Taiko: Drum Master, also known as Taiko no Tatsujin: Taiko Drum Master (太鼓の達人 TAIKO DRUM MASTER) in Japan, is a rhythm game developed and published by Namco for the Sony PlayStation 2 as part of the popular Japanese video game franchise Taiko no Tatsujin. It was released in North America in 2004, and Japan in 2005.','PS4',8.85,'https://www.metacritic.com/game/playstation-2/taiko-drum-master')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018007,'Grand Theft Auto V',2014,'Single-Player Game','The game is played from either a third-person or first-person perspective and its world is navigated on foot or by vehicle. Players control the three lead protagonists throughout single-player and switch between them both during and outside missions. The story is centred on the heist sequences, and many missions involve shooting and driving gameplay. A "wanted" system governs the aggression of law enforcement response to players who commit crimes. Grand Theft Auto Online, the games online multiplayer mode, lets up to 30 players engage in a variety of different cooperative and competitive game modes.','PC',9.5,'https://www.metacritic.com/game/pc/grand-theft-auto-v')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018008,'Minecraft',2011,'Single-Player Game','Minecraft is a 2011 sandbox video game created by Swedish game developer Markus Persson and later developed by Mojang. The game allows players to build with a variety of different blocks in a 3D procedurally generated world, requiring creativity from players.','PC',9.65,'https://www.metacritic.com/game/pc/minecraft')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018009,'Hearthstone',2014,'CAG','The game is a turn-based card game between two opponents, using constructed decks of 30 cards along with a selected hero with a unique power. Players use their limited mana crystals to play abilities or summon minions to attack the opponent, with the goal of destroying the opponents hero.','Nitendo Switch',9,'https://www.commonsensemedia.org/game-reviews/hearthstone')
insert into game(id,name,releaseYear,type,description,onplatform,rating,recommendedURL) values(2018010,'Monster Hunter',2004,'ARPG','Astera acts as a central hub where the player can buy and sell goods, manage their inventory, craft new equipment, and gain new quests. A core facet of Monster Hunter games is the construction and upgrading of armor and weapons at a forge using the monster parts and resources the player has gained from combat.','PC',9.5,'https://www.metacritic.com/game/playstation-4/monster-hunter-world')
=======
>>>>>>> 4aee0a9dc79ca370058a8de6274ca488af1e5502
-- insert into ...



-- Roles
INSERT INTO roles
VALUES
    (1, 'Volunteer');
INSERT INTO roles
VALUES
    (2, 'Secretary');
